# Generated by Django 3.2.7 on 2021-09-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('magaz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
    ]
